using System.ComponentModel.DataAnnotations;

namespace ERPSystem.Application.DTOs.Crm;

/// <summary>
/// DTO for converting a lead into an actual customer.
/// The customer code is auto-generated by the service.
/// </summary>
public class ConvertLeadDto
{
    [Required]
    public Guid LeadId { get; set; }

    [Required]
    [StringLength(200)]
    public string NameAr { get; set; } = string.Empty;

    [StringLength(200)]
    public string? NameEn { get; set; }

    [StringLength(30)]
    public string? Phone { get; set; }

    [EmailAddress]
    [StringLength(200)]
    public string? Email { get; set; }

    [StringLength(300)]
    public string? Address { get; set; }

    [StringLength(50)]
    public string? TaxNumber { get; set; }

    [StringLength(1000)]
    public string? Notes { get; set; }
}
