using ERPSystem.Application.DTOs.Reports;
using Microsoft.EntityFrameworkCore;
namespace ERPSystem.Application.Services;
public partial class ReportService
{
    private DateTime P(string? v, DateTime d) => DateTime.TryParse(v, out var x) ? x : d;
    private Guid G(string? v) => Guid.TryParse(v, out var g) ? g : Guid.Empty;
    public async Task<GenericReportTable> GetReportAsync(string key, Dictionary<string,string?> pars)
    {
        var from = P(pars.TryGetValue("from", out var f)?f:null, DateTime.Today.AddMonths(-1));
        var to = P(pars.TryGetValue("to", out var t)?t:null, DateTime.Today);
        var asOf = P(pars.TryGetValue("asOf", out var a)?a:null, DateTime.Today);
        GenericReportTable R(string ta,List<string> h,List<List<string>> rows,List<string>? tot=null,string? foot=null,bool land=true)
            => new(){ TitleAr=ta, Headers=h, Rows=rows, Totals=tot, FooterNote=foot, Landscape=land, ParamSummary=key.Contains("balance")?$"حتى {asOf:yyyy-MM-dd}":$"{from:yyyy-MM-dd} → {to:yyyy-MM-dd}"};
        switch(key)
        {
            case "trial-balance": { var tb=await GetTrialBalanceAsync(); var rows=tb.Lines.Select(l=>new List<string>{l.AccountCode,l.AccountNameAr,l.TotalDebit.ToString("N2"),l.TotalCredit.ToString("N2"),l.Balance.ToString("N2")}).ToList(); return R("ميزان المراجعة",new(){ "الرمز","الحساب","مدين","دائن","رصيد"},rows,new(){ "","الإجمالي",tb.TotalDebit.ToString("N2"),tb.TotalCredit.ToString("N2"),""}); }
            case "income-statement": { var d=await GetIncomeStatementAsync(from,to); var rows=new List<List<string>>(); rows.AddRange(d.Revenues.Select(x=>new List<string>{x.AccountCode,x.AccountNameAr,x.Amount.ToString("N2")})); rows.AddRange(d.Expenses.Select(x=>new List<string>{x.AccountCode,x.AccountNameAr,x.Amount.ToString("N2")})); return R("قائمة الدخل",new(){ "الرمز","الحساب","المبلغ"},rows,new(){ "","صافي الدخل",d.NetIncome.ToString("N2")}); }
            case "balance-sheet": { var d=await GetBalanceSheetAsync(asOf); var rows=new List<List<string>>(); rows.AddRange(d.Assets.Select(x=>new List<string>{x.AccountCode,x.AccountNameAr,x.Amount.ToString("N2")})); rows.AddRange(d.Liabilities.Select(x=>new List<string>{x.AccountCode,x.AccountNameAr,x.Amount.ToString("N2")})); rows.AddRange(d.Equity.Select(x=>new List<string>{x.AccountCode,x.AccountNameAr,x.Amount.ToString("N2")})); return R("الميزانية العمومية",new(){ "الرمز","الحساب","المبلغ"},rows,new(){ "","الأصول",d.TotalAssets.ToString("N2")},land:false); }
            case "general-ledger": { var aid=G(pars.TryGetValue("accountId",out var av)?av:null); if(aid==Guid.Empty) aid=await _context.Set<ERPSystem.Domain.Entities.Account>().Select(a=>a.Id).FirstOrDefaultAsync(); var led=await GetAccountLedgerAsync(aid,from,to); var rows=led.Lines.Select(l=>new List<string>{l.Date.ToString("yyyy-MM-dd"),l.EntryNumber,l.Description??"",l.Debit.ToString("N2"),l.Credit.ToString("N2"),l.Balance.ToString("N2")}).ToList(); return R("دفتر الأستاذ — "+led.AccountNameAr,new(){ "التاريخ","القيد","البيان","مدين","دائن","رصيد"},rows,new(){ "","","الرصيد",led.OpeningBalance.ToString("N2"),"",led.ClosingBalance.ToString("N2")}); }
            case "journal-register": { var ls=await _context.Set<ERPSystem.Domain.Entities.JournalEntryLine>().Include(l=>l.Account).Include(l=>l.JournalEntry).Where(l=>l.JournalEntry!=null && l.JournalEntry.EntryDate>=from.Date && l.JournalEntry.EntryDate<to.Date.AddDays(1)).OrderBy(l=>l.JournalEntry!.EntryDate).Take(500).ToListAsync(); var rows=ls.Select(l=>new List<string>{l.JournalEntry!.EntryDate.ToString("yyyy-MM-dd"),l.JournalEntry.EntryNumber,l.Account?.NameAr??"",l.DebitAmount.ToString("N2"),l.CreditAmount.ToString("N2"),l.JournalEntry.ReferenceNumber??""}).ToList(); return R("سجل القيود",new(){ "التاريخ","القيد","الحساب","مدين","دائن","مرجع"},rows); }
            case "cash-flow": { var ids=await _context.Set<ERPSystem.Domain.Entities.Account>().Where(a=>a.Code=="1100"||a.Code=="1110").Select(a=>a.Id).ToListAsync(); var ls=await _context.Set<ERPSystem.Domain.Entities.JournalEntryLine>().Where(l=>ids.Contains(l.AccountId) && l.JournalEntry!=null && l.JournalEntry.EntryDate>=from.Date && l.JournalEntry.EntryDate<to.Date.AddDays(1)).ToListAsync(); decimal inc=ls.Sum(l=>l.DebitAmount), exp=ls.Sum(l=>l.CreditAmount); var rows=new List<List<string>>{ new(){ "المقبوضات",inc.ToString("N2")},new(){ "المدفوعات",exp.ToString("N2")},new(){ "صافي التدفق",(inc-exp).ToString("N2")}}; return R("التدفق النقدي",new(){ "البند","المبلغ"},rows,null,"مباشر — تشغيلي فقط"); }
            case "vat-summary": { var sales=await _context.Set<ERPSystem.Domain.Entities.SalesInvoice>().Where(s=>!s.IsDeleted && s.InvoiceDate>=from.Date && s.InvoiceDate<to.Date.AddDays(1)).ToListAsync(); var purch=await _context.Set<ERPSystem.Domain.Entities.PurchaseInvoice>().Where(s=>!s.IsDeleted && s.InvoiceDate>=from.Date && s.InvoiceDate<to.Date.AddDays(1)).ToListAsync(); decimal stax=sales.Sum(s=>s.TaxAmount), ptax=purch.Sum(s=>s.TaxAmount); var rows=new List<List<string>>{ new(){ "إجمالي المبيعات",sales.Sum(s=>s.SubTotal).ToString("N2")},new(){ "ضريبة محصلة",stax.ToString("N2")},new(){ "إجمالي المشتريات",purch.Sum(s=>s.SubTotal).ToString("N2")},new(){ "ضريبة مدفوعة",ptax.ToString("N2")},new(){ "صافي الضريبة", (stax-ptax).ToString("N2")}}; return R("ملخص الضريبة",new(){ "البند","المبلغ"},rows); }
            case "sales-by-customer": { var q=await _context.Set<ERPSystem.Domain.Entities.SalesInvoice>().Where(s=>!s.IsDeleted && s.InvoiceDate>=from.Date && s.InvoiceDate<to.Date.AddDays(1)).Include(s=>s.Customer).ToListAsync(); var g=q.GroupBy(s=>s.Customer?.NameAr??s.CustomerId.ToString()).Select(x=>new{Name=x.Key,Tot=x.Sum(s=>s.TotalAmount),Cnt=x.Count()}).OrderByDescending(x=>x.Tot).ToList(); var rows=g.Select(x=>new List<string>{x.Name,x.Cnt.ToString(),x.Tot.ToString("N2")}).ToList(); return R("المبيعات حسب العميل",new(){ "العميل","عدد","الإجمالي"},rows); }
            default: return await GetReportAsyncB(key,pars,from,to,asOf,R);
        }
    }
}
